build.gradle
misc/build.gradle
settings.gradle
src/main/java/org/taktik/icure/dao/impl/GenericDAOImpl.java
src/main/java/org/taktik/icure/services/external/rest/v1/dto/RightDto.java

Bonjour Antoine,
J'ai normalement corrigé les remarques du docteur duchâteau. 
Pour le build.gradle j'ai simplement ajouté la possibilité d'exclure le frontend en rajoutant un paramètre "skipFrontend=0" lors de l'exécution de gradle.
N'hésite pas a revenir vers moi pour d'autre commentaires/remarques.
Bien à toi,
David.

Correction des Notes du docteur Duchateau pour PR

---

.travis.yml

Adding Travis script to compile the application

---

src/main/java/org/taktik/icure/entities/HealthcareParty.java
src/main/java/org/taktik/icure/services/external/rest/v1/dto/HealthcarePartyDto.java

from @vpi-b12 
ajout du userId dans hcp : https://www.pivotaltracker.com/story/show/161376510

add user to hcp

---

src/main/resources/org/taktik/icure/db/codes/CD-VACCINEINDICATION.xml

fix typo vaccin dyphterie

---

src/main/java/org/taktik/icure/services/external/rest/v1/dto/ClassificationDto.java

This is needed to display level 3 classifications.

expose the ClassificationTemplateDto properties in ClassificationDto

---

src/main/java/org/taktik/icure/dao/PatientDAO.java
src/main/java/org/taktik/icure/dao/impl/PatientDAOImpl.java
src/main/java/org/taktik/icure/dto/filter/Filter.java
src/main/java/org/taktik/icure/dto/filter/patient/PatientByHcPartyAndActiveFilter.java
src/main/java/org/taktik/icure/logic/PatientLogic.java
src/main/java/org/taktik/icure/logic/impl/PatientLogicImpl.java
src/main/java/org/taktik/icure/logic/impl/filter/patient/PatientByHcPartyAndActiveFilter.java
src/main/java/org/taktik/icure/services/external/rest/v1/dto/filter/Filter.java
src/main/java/org/taktik/icure/services/external/rest/v1/dto/filter/patient/PatientByHcPartyAndActiveFilter.java
src/main/resources/org/taktik/icure/dao/impl/js/patient/By_hcparty_active_map.js

Add filter on active / inactive patients

Add PatientByHcPartyAndActiveFilter

---

src/main/java/org/taktik/icure/logic/impl/MessageLogicImpl.java

=> The only requested input is the message id

Open door in getMessage

---

src/main/java/org/taktik/icure/dao/MedicalLocationDAO.java
src/main/java/org/taktik/icure/dao/impl/MedicalLocationDAOImpl.java
src/main/java/org/taktik/icure/entities/MedicalLocation.java
src/main/java/org/taktik/icure/entities/base/StoredDocument.java
src/main/java/org/taktik/icure/entities/base/StoredICureDocument.java
src/main/java/org/taktik/icure/logic/MedicalLocationLogic.java
src/main/java/org/taktik/icure/logic/impl/MedicalLocationLogicImpl.java
src/main/java/org/taktik/icure/services/external/rest/v1/dto/IcureDto.java
src/main/java/org/taktik/icure/services/external/rest/v1/dto/MedicalLocationDto.java
src/main/java/org/taktik/icure/services/external/rest/v1/facade/MedicalLocationFacade.java
src/main/resources/org/taktik/icure/dao/impl/js/medicallocation/By_post_code_map.js

See https://www.pivotaltracker.com/story/show/162918261

Add medical location notion for PMG

---

src/main/java/org/taktik/icure/dao/impl/CouchDbICureRepositorySupport.java

See https://www.pivotaltracker.com/story/show/163070467/comments/198218508

Harden the queryView against possible NPEs

---

src/main/java/org/taktik/icure/entities/base/StoredDocument.java

Fix a small error, the property was not named correctly.
https://github.com/antoinepairet/medispring/issues/1642

[HOTFIX] Fix bad naming

---

src/main/java/org/taktik/icure/services/external/rest/v1/facade/UserFacade.java

This fixes the bad return value on the method findByHcparty

Fix method findByHcparty

---

src/main/java/org/taktik/icure/entities/MedicalLocation.java
src/main/java/org/taktik/icure/services/external/rest/v1/dto/MedicalLocationDto.java

add agendaIds in MedicalLocation

---

src/main/java/org/taktik/icure/be/format/logic/impl/HealthOneLogicImpl.java

[MS-123] Fix parts7 ignored while present

---

src/main/java/org/taktik/icure/db/StringUtils.java

[MS-226] add missing score update on CP1252 superscript-three

---

src/main/java/org/taktik/icure/be/format/logic/impl/HealthOneLogicImpl.java

https://medispring.atlassian.net/browse/MS-530

[MS-530 Support] "+++" and "---" (and "++++" and "----") in critical HealthOne values

---

src/main/java/org/taktik/icure/dao/ContactDAO.java
src/main/java/org/taktik/icure/dao/impl/ContactDAOImpl.java
src/main/java/org/taktik/icure/logic/ContactLogic.java
src/main/java/org/taktik/icure/logic/impl/ContactLogicImpl.java
src/main/java/org/taktik/icure/services/external/rest/v1/facade/ContactFacade.java

This PR is a copy from a local branch (not from B12 repo)

Add end point for contact list by opening date

---

src/main/java/org/taktik/icure/services/external/rest/v1/facade/MessageFacade.java

https://medispring.atlassian.net/browse/MS-459

MS-459 Modify the HCP id filter logic at the level of the message by transport guid

---

src/main/java/org/taktik/icure/entities/Message.java
src/main/java/org/taktik/icure/logic/MessageLogic.java
src/main/java/org/taktik/icure/logic/impl/MessageLogicImpl.java
src/main/java/org/taktik/icure/services/external/rest/v1/dto/MessageDto.java
src/main/java/org/taktik/icure/services/external/rest/v1/dto/MessageReadStatus.java
src/main/java/org/taktik/icure/services/external/rest/v1/dto/MessagesReadStatusUpdate.java
src/main/java/org/taktik/icure/services/external/rest/v1/facade/MessageFacade.java

https://github.com/antoinepairet/icc-api/pull/127

MS-483 As a GP, I can differentiate the message I have read from the unread

---

src/main/java/org/taktik/icure/services/external/rest/v1/dto/TypedValueDto.java

This pull requests fixes a merge issue where the booleanValue getter and setter was wrong

Fix TypedValueDto

---

src/main/java/org/taktik/icure/entities/Patient.java
src/main/java/org/taktik/icure/services/external/rest/v1/dto/PatientDto.java

Added the nonDuplicateIds property to the Patient and PatientDto classes
https://medispring.atlassian.net/browse/MS-871

MS-871 Add nonDuplicateIds property to Patient and PatientDto classes

---

src/main/java/org/taktik/icure/be/format/logic/impl/HealthOneLogicImpl.java
src/test/kotlin/org/taktik/icure/be/format/logic/impl/HealthOneLogicImplTest.kt

If a date if before 1800, it's integrated in this way :
- A birthDate as null
- A demandDate as now()

[MS-1202] Dates before 1800 are errors

---

src/test/kotlin/org/taktik/icure/be/ehealth/logic/kmehr/v20161201/KmehrExportTest.kt

It's linked with [MS-1261], currently tests are failing but after merging the correction done in MS-1261 the tests do succeed
[MS-1261]: https://medispring.atlassian.net/browse/MS-1261

[linked MS-1261] Tests for KmehrExport.createItemWithContent

---

src/main/java/org/taktik/icure/dao/HealthElementDAO.java
src/main/java/org/taktik/icure/dao/impl/HealthElementDAOImpl.java
src/main/java/org/taktik/icure/dto/filter/healthelement/HealthElementByHcPartyCodeFilter.java
src/main/java/org/taktik/icure/logic/HealthElementLogic.java
src/main/java/org/taktik/icure/logic/impl/HealthElementLogicImpl.java
src/main/java/org/taktik/icure/logic/impl/filter/healthelement/HealthElementByHcPartyCodeFilter.java
src/main/java/org/taktik/icure/services/external/rest/v1/dto/filter/Filter.java
src/main/java/org/taktik/icure/services/external/rest/v1/dto/filter/healthelement/HealthElementByHcPartyCodeFilter.java
src/main/java/org/taktik/icure/services/external/rest/v1/facade/HealthElementFacade.java
src/main/resources/org/taktik/icure/dao/impl/js/healthelement/By_hcparty_code_map.js

https://medispring.atlassian.net/browse/MS-1484

[MS-1484] Filter health elements by health care party id and codes

---

src/main/kotlin/org/taktik/icure/be/ehealth/logic/kmehr/medicationscheme/impl/v20161201/MedicationSchemeExport.kt

Jira tickets: 
https://medispring.atlassian.net/browse/TAK-140
https://medispring.atlassian.net/browse/MS-2081
When a medication schema is exported:
1. the <transaction/> <author/> for the CD-TRANSACTION : medicationscheme was changed with the sender instead of the patient author
2. the <transaction/> <author/> for the CD-TRANSACTION : medicationschemeelement was changed with the service author instead of the patient author

TAK-140 Use the service author instead of patient author for transactions author elements

---

src/main/java/org/taktik/icure/entities/MedicalLocation.java
src/main/java/org/taktik/icure/services/external/rest/v1/dto/MedicalLocationDto.java

Simple MedicalLocation (model and DTO) modification to handle a standard HashMap options.

[MS-2589] Add HashMap options property to the MedicalLocation model and DTO

---

src/main/kotlin/org/taktik/icure/be/ehealth/logic/kmehr/note/KmehrNoteLogic.kt
src/main/kotlin/org/taktik/icure/be/ehealth/logic/kmehr/note/impl/v20161201/KmehrNoteLogicImpl.kt
src/main/kotlin/org/taktik/icure/services/external/rest/v1/facade/be/KmehrFacade.kt

Request recipient SSIN in createNote in order to build a complete HCPParty in the corresponding Kmehr message.

[MS-3260] Send contactreport to hub

---

src/main/kotlin/org/taktik/icure/be/ehealth/logic/kmehr/smf/impl/v23g/SoftwareMedicalFileExport.kt

To allow to patch correctly only the newest version of a contact.
In the previous version of the implementation all contacts were
included instead of only the latest versions.

MS-3483 Decrypt contacts in a single request;
